services:
  mysql:
    image: mysql:9.1
    container_name: paybis_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - paybis_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paybis_php
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    networks:
      - paybis_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}

  nginx:
    image: nginx:1.27-alpine
    container_name: paybis_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - paybis_network
    depends_on:
      - php

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paybis_scheduler
    command: php bin/console messenger:consume scheduler_currency_rates -vv
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    networks:
      - paybis_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    container_name: paybis_dozzle
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "name=paybis_"
    networks:
      - paybis_network

volumes:
  mysql_data:

networks:
  paybis_network:
    driver: bridge
